export const mockData = [
  {
    image: 'src/assets/browsing/mock/mock1.png',
    name: '무선 이어버드 이어버드 이어버드',
    city: '서울',
    district: '강남구',
    discount: 20,
    price: '150,000',
    reviewPoint: 4.5,
    reviewCount: 1200,
  },
  {
    image: 'src/assets/browsing/mock/mock2.png',
    name: '스마트폰 거치대',
    city: '부산',
    district: '해운대구',
    discount: 10,
    price: '20,000',
    reviewPoint: 4.0,
    reviewCount: 300,
  },
  {
    image: 'src/assets/browsing/mock/mock3.png',
    name: '블루투스 스피커',
    city: '인천',
    district: '남구',
    discount: 15,
    price: '45,000',
    reviewPoint: 4.7,
    reviewCount: 800,
  },
  {
    image: 'src/assets/browsing/mock/mock4.png',
    name: '피트니스 트래커',
    city: '대구',
    district: '수성구',
    discount: 25,
    price: '120,000',
    reviewPoint: 4.3,
    reviewCount: 500,
  },
  {
    image: 'src/assets/browsing/mock/mock5.png',
    name: '노트북 스탠드',
    city: '대전',
    district: '서구',
    discount: 5,
    price: '35,000',
    reviewPoint: 4.1,
    reviewCount: 150,
  },
  {
    image: 'src/assets/browsing/mock/mock6.png',
    name: '노이즈 캔슬링 헤드폰',
    city: '광주',
    district: '북구',
    discount: 30,
    price: '250,000',
    reviewPoint: 4.8,
    reviewCount: 950,
  },
] as const
