export const mockData1 = [
  {
    image: 'src/assets/home/mock/mock1.png',
    name: '무선 이어버드 이어버드 이어버드',
    city: '서울',
    district: '강남구',
    discount: 20,
    price: '150,000',
    reviewPoint: 4.5,
    reviewCount: 1200,
  },
  {
    image: 'src/assets/home/mock/mock2.png',
    name: '스마트폰 거치대',
    city: '부산',
    district: '해운대구',
    discount: 10,
    price: '20,000',
    reviewPoint: 4.0,
    reviewCount: 300,
  },
  {
    image: 'src/assets/home/mock/mock3.png',
    name: '블루투스 스피커',
    city: '인천',
    district: '남구',
    discount: 15,
    price: '45,000',
    reviewPoint: 4.7,
    reviewCount: 800,
  },
  {
    image: 'src/assets/home/mock/mock4.png',
    name: '피트니스 트래커',
    city: '대구',
    district: '수성구',
    discount: 25,
    price: '120,000',
    reviewPoint: 4.3,
    reviewCount: 500,
  },
  {
    image: 'src/assets/home/mock/mock5.png',
    name: '노트북 스탠드',
    city: '대전',
    district: '서구',
    discount: 5,
    price: '35,000',
    reviewPoint: 4.1,
    reviewCount: 150,
  },
  {
    image: 'src/assets/home/mock/mock6.png',
    name: '노이즈 캔슬링 헤드폰',
    city: '광주',
    district: '북구',
    discount: 30,
    price: '250,000',
    reviewPoint: 4.8,
    reviewCount: 950,
  },
] as const

export const mockData2 = [
  {
    image: 'src/assets/home/mock/mock-bg-1.png',
    name: '무선 이어버드 이어버드 이어버드',
    city: '서울',
    district: '강남구',
    discount: 20,
    price: '150,000',
    reviewPoint: 4.5,
    reviewCount: 1200,
  },
  {
    image: 'src/assets/home/mock/mock-bg-2.png',
    name: '스마트폰 거치대',
    city: '부산',
    district: '해운대구',
    discount: 10,
    price: '20,000',
    reviewPoint: 4.0,
    reviewCount: 300,
  },
  {
    image: 'src/assets/home/mock/mock-bg-3.png',
    name: '블루투스 스피커',
    city: '인천',
    district: '남구',
    discount: 15,
    price: '45,000',
    reviewPoint: 4.7,
    reviewCount: 800,
  },
  {
    image: 'src/assets/home/mock/mock-bg-4.png',
    name: '피트니스 트래커',
    city: '대구',
    district: '수성구',
    discount: 25,
    price: '120,000',
    reviewPoint: 4.3,
    reviewCount: 500,
  },
  {
    image: 'src/assets/home/mock/mock-bg-5.png',
    name: '노트북 스탠드',
    city: '대전',
    district: '서구',
    discount: 5,
    price: '35,000',
    reviewPoint: 4.1,
    reviewCount: 150,
  },
  {
    image: 'src/assets/home/mock/mock-bg-6.png',
    name: '노이즈 캔슬링 헤드폰',
    city: '광주',
    district: '북구',
    discount: 30,
    price: '250,000',
    reviewPoint: 4.8,
    reviewCount: 950,
  },
] as const

export const mockData3 = [
  'https://img-cdn.pixlr.com/image-generator/history/65bb506dcb310754719cf81f/ede935de-1138-4f66-8ed7-44bd16efc709/medium.webp',
  'https://images.unsplash.com/photo-1575936123452-b67c3203c357?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8aW1hZ2V8ZW58MHx8MHx8fDA%3D',
  'https://img.freepik.com/free-photo/painting-mountain-lake-with-mountain-background_188544-9126.jpg',
  'https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885_1280.jpg',
  'https://www.befunky.com/images/prismic/1f427434-7ca0-46b2-b5d1-7d31843859b6_funky-focus-red-flower-field-after.jpeg?auto=avif,webp&format=jpg&width=863',
]
